export { Module, ResourceRegistry, registry } from './registry'
export { openAPIModule } from './modules/openapi'
export { lucideModule } from './modules/icons'
export { nvimModule } from './modules/nvim'
export { tmuxModule } from './modules/tmux'
export { shadcnModule } from './modules/shadcn'
