export { ResourceModule, BaseResourceModule } from './base'
export { ResourceRegistry, registry } from './registry'
export { OpenAPIResource } from './modules/openapi'
export { IconsResource } from './modules/icons'
export { NvimResource } from './modules/nvim'
export { TmuxResource } from './modules/tmux'
